arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - en
  - ur
untranslated-messages-file: lib/l10n/UNTRANSLATED.txt

# Keep getters non-nullable
nullable-getter: false
