import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../../core/constants/app_constants.dart';
import '../models/message_model.dart';
import '../models/chat_model.dart';
import '../services/chat_service.dart';
import '../../cases/models/consultation_model.dart';
import '../../cases/services/consultation_service.dart';

class ChatScreen extends StatefulWidget {
  final String conversationId;
  final Map<String, dynamic> lawyerData;

  const ChatScreen({
    super.key,
    required this.conversationId,
    required this.lawyerData,
  });

  @override
  State<ChatScreen> createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> {
  final _chatService = ChatService();
  final _messageController = TextEditingController();
  final _scrollController = ScrollController();
  final _currentUser = FirebaseAuth.instance.currentUser;
  String? _userRole;
  int _messageLimit = 50;

  @override
  void initState() {
    super.initState();
    _getUserRole();
    _markAsRead();
    _scrollController.addListener(_onScroll);
  }

  Future<void> _markAsRead() async {
    if (_currentUser == null) return;
    await _chatService.markAsRead(widget.conversationId, _currentUser.uid);
  }

  void _onScroll() {
    if (_scrollController.position.pixels >= _scrollController.position.maxScrollExtent - 200) {
      if (mounted) {
        setState(() {
          _messageLimit += 50;
        });
      }
    }
  }

  Future<void> _getUserRole() async {
    if (_currentUser == null) return;
    final doc = await FirebaseFirestore.instance.collection('users').doc(_currentUser.uid).get();
    if (doc.exists) {
      if (!context.mounted) return;
      setState(() {
        _userRole = doc.data()?['role'];
      });
    }
  }

  @override
  void dispose() {
    _messageController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  void _sendMessage() async {
    if (_messageController.text.trim().isEmpty || _currentUser == null) return;

    final text = _messageController.text.trim();
    _messageController.clear();

    try {
      // Create chat document if it's a new virtual chat
      final chatDoc = await FirebaseFirestore.instance.collection('chats').doc(widget.conversationId).get();
      if (!chatDoc.exists && _userRole != 'lawyer') {
        final userData = await FirebaseFirestore.instance.collection('users').doc(_currentUser.uid).get();
        final lawyerId = widget.lawyerData['lawyerId'] ?? widget.lawyerData['id'] ?? '';
        final chat = ChatModel(
          id: widget.conversationId,
          clientId: _currentUser.uid,
          lawyerId: lawyerId,
          clientName: userData.data()?['fullName'] ?? 'Client',
          lawyerName: widget.lawyerData['lawyerName'] ?? widget.lawyerData['name'] ?? 'Lawyer',
          clientAvatar: userData.data()?['photoUrl'],
          lawyerAvatar: widget.lawyerData['lawyerAvatar'] ?? widget.lawyerData['photoUrl'],
          lastMessage: text,
          lastMessageTime: DateTime.now(),
        );
        final chatMap = chat.toMap();
        chatMap['participants'] = [_currentUser.uid, lawyerId];
        await FirebaseFirestore.instance.collection('chats').doc(widget.conversationId).set(chatMap);
      }

      final message = MessageModel(
        id: '', // Generated by Firestore
        senderId: _currentUser.uid,
        text: text,
        timestamp: DateTime.now(),
      );

      await _chatService.sendMessage(
        widget.conversationId,
        message,
        _userRole == 'lawyer',
      );
    } catch (e) {
      if (!context.mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(e.toString()),
          backgroundColor: AppColors.error,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;
    final isClient = _userRole == 'client';
    final otherName = isClient ? widget.lawyerData['lawyerName'] : widget.lawyerData['clientName'];
    final otherAvatar = isClient ? widget.lawyerData['lawyerAvatar'] : widget.lawyerData['clientAvatar'];

    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      appBar: AppBar(
        backgroundColor: AppColors.primary,
        foregroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const PhosphorIcon(PhosphorIconsRegular.arrowLeft),
          onPressed: () => context.pop(),
        ),
        title: Row(
          children: [
            CircleAvatar(
              radius: 18,
              backgroundColor: Colors.white24,
              backgroundImage: otherAvatar != null ? NetworkImage(otherAvatar) : null,
              child: otherAvatar == null ? Text(otherName?[0] ?? '?', style: const TextStyle(color: Colors.white)) : null,
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    otherName ?? 'Chat',
                    style: textTheme.titleMedium?.copyWith(
                      color: Colors.white,
                      fontWeight: FontWeight.w700,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                  Text(
                    'Active session',
                    style: textTheme.bodySmall?.copyWith(
                      color: Colors.white.withValues(alpha: 0.8),
                      fontSize: 10,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
      body: Column(
        children: [
          Expanded(
            child: StreamBuilder<List<MessageModel>>(
              stream: _chatService.streamMessages(widget.conversationId, limit: _messageLimit),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting && _messageLimit == 50) {
                  return const Center(child: CircularProgressIndicator());
                }
                
                final messages = snapshot.data ?? [];
                
                // Real-time unread count clearing: Mark as read if we're looking at the screen
                if (messages.isNotEmpty && _currentUser != null && mounted) {
                  Future.microtask(() => _markAsRead());
                }
                
                if (messages.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        PhosphorIcon(PhosphorIconsRegular.chatCenteredDots, size: 64, color: AppColors.textLight),
                        const SizedBox(height: AppSpacing.md),
                        Text('No messages yet', style: textTheme.bodyLarge?.copyWith(color: AppColors.textSecondary)),
                      ],
                    ),
                  );
                }

                return ListView.builder(
                  controller: _scrollController,
                  padding: const EdgeInsets.all(AppSpacing.md),
                  reverse: true,
                  itemCount: messages.length,
                  itemBuilder: (context, index) {
                    return _MessageBubble(
                      message: messages[index],
                      isMe: messages[index].senderId == _currentUser?.uid,
                      userRole: _userRole,
                      conversationId: widget.conversationId,
                    );
                  },
                );
              },
            ),
          ),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: AppSpacing.md, vertical: AppSpacing.sm),
            decoration: BoxDecoration(
              color: AppColors.surface,
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.05),
                  blurRadius: 4,
                  offset: const Offset(0, -2),
                )
              ],
            ),
            child: SafeArea(
              child: Row(
                children: [
                  Expanded(
                    child: TextField(
                      controller: _messageController,
                      decoration: InputDecoration(
                        hintText: 'Type a message...',
                        hintStyle: textTheme.bodyMedium?.copyWith(color: AppColors.textLight),
                        filled: true,
                        fillColor: AppColors.grey200,
                        border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppRadius.full), borderSide: BorderSide.none),
                        contentPadding: const EdgeInsets.symmetric(horizontal: AppSpacing.md, vertical: AppSpacing.sm),
                      ),
                      maxLines: null,
                      textInputAction: TextInputAction.send,
                      onSubmitted: (_) => _sendMessage(),
                    ),
                  ),
                  const SizedBox(width: AppSpacing.sm),
                  Container(
                    decoration: const BoxDecoration(color: AppColors.secondary, shape: BoxShape.circle),
                    child: IconButton(
                      icon: const PhosphorIcon(PhosphorIconsRegular.paperPlaneTilt, color: AppColors.textPrimary),
                      onPressed: _sendMessage,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _MessageBubble extends StatefulWidget {
  final MessageModel message;
  final bool isMe;
  final String? userRole;
  final String conversationId;

  const _MessageBubble({
    required this.message, 
    required this.isMe,
    this.userRole,
    required this.conversationId,
  });

  @override
  State<_MessageBubble> createState() => _MessageBubbleState();
}

class _MessageBubbleState extends State<_MessageBubble> {
  bool _isLoading = false;

  @override
  Widget build(BuildContext context) {
    if (widget.message.type == 'consultation_booking' || widget.message.type == 'consultation_accepted') {
      return _buildConsultationCard(context);
    }
    if (widget.message.type == 'cancellation_request' || 
        widget.message.type == 'cancellation_accepted' || 
        widget.message.type == 'cancellation_rejected' ||
        widget.message.type == 'lawyer_direct_cancellation') {
      return _buildCancellationCard(context);
    }
    return _buildTextBubble(context);
  }

  Widget _buildCancellationCard(BuildContext context) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;
    final metadata = widget.message.metadata ?? {};
    
    final isLawyer = widget.userRole == 'lawyer';
    final type = widget.message.type;
    final topic = metadata['topic'] ?? 'Consultation';
    final reason = metadata['cancellationReason'] ?? 'No reason provided';
    final status = metadata['status'] ?? 'pending';
    
    // Determine title and color based on message type
    String cardTitle = 'Cancellation Requested';
    Color cardColor = AppColors.error;
    IconData cardIcon = PhosphorIconsFill.warningCircle;

    if (type == 'cancellation_accepted') {
      cardTitle = 'Cancellation Approved';
      cardColor = AppColors.success;
      cardIcon = PhosphorIconsFill.checkCircle;
    } else if (type == 'cancellation_rejected') {
      cardTitle = 'Cancellation Rejected';
      cardColor = AppColors.error;
      cardIcon = PhosphorIconsFill.xCircle;
    } else if (type == 'lawyer_direct_cancellation') {
      cardTitle = 'Consultation Cancelled';
      cardColor = AppColors.error;
      cardIcon = PhosphorIconsFill.prohibit;
    }

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: AppSpacing.md),
      child: Center(
        child: Container(
          width: MediaQuery.of(context).size.width * 0.85,
          padding: const EdgeInsets.all(AppSpacing.md),
          decoration: BoxDecoration(
            color: AppColors.error.withValues(alpha: 0.05),
            borderRadius: BorderRadius.circular(AppRadius.lg),
            border: Border.all(color: AppColors.error.withValues(alpha: 0.5), width: 1.5),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  PhosphorIcon(cardIcon, color: cardColor, size: 24),
                  const SizedBox(width: AppSpacing.sm),
                  Text(
                    cardTitle,
                    style: textTheme.titleMedium?.copyWith(
                      color: cardColor,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: AppSpacing.md),
              Text(topic, style: textTheme.titleSmall, textAlign: TextAlign.center),
              const SizedBox(height: 4),
              Text('Reason: $reason', style: textTheme.bodySmall?.copyWith(fontStyle: FontStyle.italic), textAlign: TextAlign.center),
              const SizedBox(height: AppSpacing.md),
              
              if (type == 'cancellation_request' && status == 'pending' && isLawyer) ...[
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Expanded(
                      child: OutlinedButton(
                        onPressed: _isLoading ? null : () => _handleCancelDecision(false),
                        style: OutlinedButton.styleFrom(
                          foregroundColor: AppColors.primary,
                          side: const BorderSide(color: AppColors.primary),
                        ),
                        child: const Text('Reject'),
                      ),
                    ),
                    const SizedBox(width: AppSpacing.sm),
                    Expanded(
                      child: FilledButton(
                        onPressed: _isLoading ? null : () => _handleCancelDecision(true),
                        style: FilledButton.styleFrom(backgroundColor: AppColors.error),
                        child: _isLoading 
                          ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                          : const Text('Approve'),
                      ),
                    ),
                  ],
                ),
              ] else if (type == 'cancellation_request') ...[
                Text(
                  status == 'accepted' ? 'Cancellation Approved.' : status == 'rejected' ? 'Cancellation Rejected.' : 'Pending Lawyer Approval.',
                  style: textTheme.bodySmall?.copyWith(
                    color: status == 'accepted' ? AppColors.success : status == 'rejected' ? AppColors.error : AppColors.warning,
                    fontWeight: FontWeight.bold,
                  ),
                  textAlign: TextAlign.center,
                ),
              ] else ...[
                Text(
                  widget.message.text,
                  style: textTheme.bodySmall,
                  textAlign: TextAlign.center,
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildConsultationCard(BuildContext context) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;
    final isAcceptedType = widget.message.type == 'consultation_accepted';
    final metadata = widget.message.metadata ?? {};
    
    // Check if we need to show lawyer action buttons
    final isLawyer = widget.userRole == 'lawyer';
    final isBooking = widget.message.type == 'consultation_booking';
    final isPending = metadata['status'] == 'pending';
    final isRejected = metadata['status'] == 'rejected';
    final showActions = isLawyer && isBooking && isPending;

    final isAccepted = isAcceptedType || metadata['status'] == 'accepted';
    final isCancelled = metadata['status'] == 'cancelled';
    final isCancellationRequested = metadata['status'] == 'cancellation_requested';
    
    final topic = metadata['topic'] ?? 'Consultation';
    final isOnline = metadata['meetingType'] == 'online' || metadata['meetingType'] == 'video';
    final meetingTypeDisplay = isOnline ? 'Video Call' : 'In-Person';
    final location = metadata['location'] as String?;
    final dateStr = metadata['date'] as String?;
    final timeStr = metadata['time'] ?? '';
    final price = metadata['price'];

    DateTime? date;
    if (dateStr != null) {
      date = DateTime.tryParse(dateStr);
    }
    
    final dateDisplay = date != null ? '${date.day}/${date.month}/${date.year}' : 'Unknown Date';

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: AppSpacing.md),
      child: Center(
        child: Container(
          width: MediaQuery.of(context).size.width * 0.85,
          padding: const EdgeInsets.all(AppSpacing.md),
          decoration: BoxDecoration(
            color: isCancelled 
                ? Colors.grey.withValues(alpha: 0.05) 
                : isAccepted 
                    ? AppColors.success.withValues(alpha: 0.05) 
                    : AppColors.surface,
            borderRadius: BorderRadius.circular(AppRadius.lg),
            border: Border.all(
                color: isCancelled 
                    ? Colors.grey.withValues(alpha: 0.5) 
                    : isAccepted 
                        ? AppColors.success.withValues(alpha: 0.5) 
                        : AppColors.secondary.withValues(alpha: 0.5), 
                width: 1.5
            ),
            boxShadow: [
              BoxShadow(
                color: (isCancelled ? Colors.grey : isAccepted ? AppColors.success : AppColors.secondary).withValues(alpha: 0.1),
                blurRadius: 10,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  PhosphorIcon(
                    isCancelled 
                        ? PhosphorIconsFill.prohibit 
                        : isAccepted 
                            ? PhosphorIconsFill.checkCircle 
                            : PhosphorIconsFill.calendarCheck, 
                    color: isCancelled 
                        ? Colors.grey 
                        : isAccepted 
                            ? AppColors.success 
                            : AppColors.secondary, 
                    size: 24
                  ),
                  const SizedBox(width: AppSpacing.sm),
                  Text(
                    isCancelled 
                        ? 'Consultation Cancelled' 
                        : isAccepted 
                            ? 'Consultation Accepted' 
                            : 'Consultation Booked',
                    style: textTheme.titleMedium?.copyWith(
                      color: isCancelled 
                          ? Colors.grey 
                          : isAccepted 
                              ? AppColors.success 
                              : AppColors.secondary,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: AppSpacing.md),
              Container(
                padding: const EdgeInsets.all(AppSpacing.sm),
                decoration: BoxDecoration(
                  color: AppColors.background,
                  borderRadius: BorderRadius.circular(AppRadius.md),
                ),
                child: Column(
                  children: [
                    Text(
                      topic,
                      style: textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: AppSpacing.sm),
                    Text(
                      '$dateDisplay at $timeStr',
                      style: textTheme.bodyMedium?.copyWith(color: AppColors.textSecondary),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      meetingTypeDisplay,
                      style: textTheme.labelLarge?.copyWith(
                        color: AppColors.primary,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                    if (!isOnline) ...[
                      const SizedBox(height: 4),
                      Text(
                        location != null && location.isNotEmpty ? 'Location: $location' : '(Location to be decided)',
                        style: textTheme.bodySmall?.copyWith(
                          color: AppColors.textSecondary,
                          fontStyle: FontStyle.italic,
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  ],
                ),
              ),
              const SizedBox(height: AppSpacing.md),
              if (price != null) ...[
                Text(
                  'Price: PKR $price',
                  style: textTheme.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w600,
                    color: AppColors.textPrimary,
                  ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: AppSpacing.xs),
              ],
              Text(
                isCancelled
                    ? 'This consultation has been cancelled.'
                    : isAccepted 
                        ? 'Ready on schedule. Please prepare any materials.' 
                        : isRejected 
                            ? 'Consultation request was declined.'
                            : isCancellationRequested
                                ? 'Status: Cancellation Requested'
                                : 'Status: Pending Lawyer Approval',
                style: textTheme.bodySmall?.copyWith(
                  color: isCancelled 
                      ? Colors.grey 
                      : isAccepted 
                          ? AppColors.success 
                          : isRejected 
                              ? AppColors.error 
                              : AppColors.warning,
                  fontStyle: FontStyle.italic,
                  fontWeight: isCancellationRequested ? FontWeight.bold : null,
                ),
                textAlign: TextAlign.center,
              ),
              if (showActions) ...[
                const SizedBox(height: AppSpacing.md),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Expanded(
                      child: OutlinedButton(
                        onPressed: _isLoading ? null : _handleReject,
                        style: OutlinedButton.styleFrom(
                          foregroundColor: AppColors.error,
                          side: const BorderSide(color: AppColors.error),
                        ),
                        child: const Text('Decline'),
                      ),
                    ),
                    const SizedBox(width: AppSpacing.sm),
                    Expanded(
                      child: FilledButton(
                        onPressed: _isLoading ? null : _handleAccept,
                        style: FilledButton.styleFrom(
                          backgroundColor: AppColors.success,
                        ),
                        child: _isLoading 
                          ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                          : const Text('Accept'),
                      ),
                    ),
                  ],
                ),
              ] else if ((isAccepted || isBooking && !showActions) && !isCancelled) ...[
                const SizedBox(height: AppSpacing.md),
                FilledButton.tonalIcon(
                  onPressed: () {
                    final caseId = metadata['caseId'] ?? 'standalone';
                    final consultationId = metadata['consultationId'];
                    if (consultationId != null) {
                      context.push('/consultation-details/$caseId/$consultationId');
                    } else {
                      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Invalid consultation data')));
                    }
                  },
                  icon: const PhosphorIcon(PhosphorIconsRegular.fileText, size: 18),
                  label: const Text('Open Consultation Details'),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextBubble(BuildContext context) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;

    return Padding(
      padding: const EdgeInsets.only(bottom: AppSpacing.sm),
      child: Row(
        mainAxisAlignment: widget.isMe ? MainAxisAlignment.end : MainAxisAlignment.start,
        children: [
          Container(
            constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.75),
            padding: const EdgeInsets.symmetric(horizontal: AppSpacing.md, vertical: AppSpacing.sm),
            decoration: BoxDecoration(
              color: widget.isMe ? AppColors.primary : AppColors.surface,
              borderRadius: BorderRadius.only(
                topLeft: const Radius.circular(AppRadius.md),
                topRight: const Radius.circular(AppRadius.md),
                bottomLeft: Radius.circular(widget.isMe ? AppRadius.md : 4),
                bottomRight: Radius.circular(widget.isMe ? 4 : AppRadius.md),
              ),
              border: widget.isMe ? null : Border.all(color: AppColors.grey300, width: 1),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  widget.message.text,
                  style: textTheme.bodyMedium?.copyWith(
                    color: widget.isMe ? Colors.white : AppColors.textPrimary,
                    height: 1.4,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  _formatTime(widget.message.timestamp),
                  style: textTheme.labelSmall?.copyWith(
                    color: widget.isMe ? Colors.white.withValues(alpha: 0.7) : AppColors.textLight,
                    fontSize: 10,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  String _formatTime(DateTime time) {
    final hour = time.hour > 12 ? time.hour - 12 : (time.hour == 0 ? 12 : time.hour);
    final period = time.hour >= 12 ? 'PM' : 'AM';
    return '$hour:${time.minute.toString().padLeft(2, '0')} $period';
  }

  Future<void> _handleAccept() async {
    if (_isLoading) return;
    final metadata = widget.message.metadata ?? {};
    final caseId = metadata['caseId'];
    final consultationId = metadata['consultationId'];
    final status = metadata['status'];

    if (status == 'accepted' || status == 'rejected') return;
    
    if (caseId == null || consultationId == null) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Cannot process legacy booking format. Please ask client to re-book.')));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final currentUser = FirebaseAuth.instance.currentUser;
      final userDoc = currentUser != null 
          ? await FirebaseFirestore.instance.collection('users').doc(currentUser.uid).get()
          : null;
      final userName = userDoc?.data()?['fullName'] ?? 'Lawyer';

      String? location;
      if (metadata['meetingType'] == 'in_person' || metadata['meetingType'] == 'in_person') {
         if (!mounted) return;
         location = await _showLocationDialog(context);
         if (location == null) {
           setState(() => _isLoading = false);
           return;
         }
      }

      await ConsultationService().acceptConsultation(
        caseId,
        consultationId,
        currentUser?.uid ?? '',
        userName,
        widget.userRole ?? 'lawyer',
        location: location,
      );

      await FirebaseFirestore.instance
          .collection('chats')
          .doc(widget.conversationId)
          .collection('messages')
          .doc(widget.message.id)
          .update({'metadata.status': 'accepted'});
    } catch (e) {
      if (!context.mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _handleReject() async {
    if (_isLoading) return;
    final metadata = widget.message.metadata ?? {};
    final caseId = metadata['caseId'];
    final consultationId = metadata['consultationId'];
    final status = metadata['status'];

    if (status == 'accepted' || status == 'rejected') return;

    if (caseId == null || consultationId == null) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Cannot process legacy booking format. Please ask client to re-book.')));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final currentUser = FirebaseAuth.instance.currentUser;
      final userDoc = currentUser != null 
          ? await FirebaseFirestore.instance.collection('users').doc(currentUser.uid).get()
          : null;
      final userName = userDoc?.data()?['fullName'] ?? 'Lawyer';

      if (!mounted) return;
      final reason = await _showReasonDialog(context, 'Reject');
      if (reason == null) {
        setState(() => _isLoading = false);
        return;
      }

      await ConsultationService().rejectConsultation(
        caseId, 
        consultationId, 
        currentUser?.uid ?? '',
        userName,
        widget.userRole ?? 'lawyer',
        reason.isEmpty ? null : reason
      );

      await FirebaseFirestore.instance
          .collection('chats')
          .doc(widget.conversationId)
          .collection('messages')
          .doc(widget.message.id)
          .update({'metadata.status': 'rejected'});
          
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _handleCancelDecision(bool accept) async {
    if (_isLoading) return;
    final metadata = widget.message.metadata ?? {};
    final caseId = metadata['caseId'];
    final consultationId = metadata['consultationId'];
    final status = metadata['status'];

    if (status == 'accepted' || status == 'rejected') return;
    
    setState(() => _isLoading = true);
    try {
      final currentUser = FirebaseAuth.instance.currentUser;
      final userDoc = currentUser != null 
          ? await FirebaseFirestore.instance.collection('users').doc(currentUser.uid).get()
          : null;
      final userName = userDoc?.data()?['fullName'] ?? 'Lawyer';

      // To run resolveClientCancellation, we need the consultation model
      // But we can just use an empty object with the ID. 
      // Wait, resolveClientCancellation expects ConsultationModel. 
      // Let's fetch it first.
      ConsultationModel? consult;
      if (caseId != null && consultationId != null) {
         consult = await ConsultationService().getConsultation(caseId, consultationId);
      } else if (consultationId != null) {
         // If caseId is not in metadata, we might need a workaround, but let's assume it is.
         final caseIdFromMessage = metadata['caseId'];
         consult = await ConsultationService().getConsultation(caseIdFromMessage ?? 'unknown', consultationId);
      }
      
      if (consult != null) {
        await ConsultationService().resolveClientCancellation(
          consult,
          currentUser?.uid ?? '',
          userName,
          accept,
        );
      }

      await FirebaseFirestore.instance
          .collection('chats')
          .doc(widget.conversationId)
          .collection('messages')
          .doc(widget.message.id)
          .update({'metadata.status': accept ? 'accepted' : 'rejected'});
          
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<String?> _showLocationDialog(BuildContext context) async {
    final controller = TextEditingController();
    return showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Set Meeting Location'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Please provide the address or location for this in-person consultation.',
              style: TextStyle(fontSize: 13, color: AppColors.textSecondary),
            ),
            const SizedBox(height: AppSpacing.md),
            TextField(
              controller: controller,
              decoration: InputDecoration(
                hintText: 'Enter complete address...',
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppRadius.sm)),
              ),
              maxLines: 3,
              autofocus: true,
            ),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
          FilledButton(onPressed: () => Navigator.pop(context, controller.text), child: const Text('Accept & Set Location')),
        ],
      ),
    );
  }

  Future<String?> _showReasonDialog(BuildContext context, String action) async {
    final controller = TextEditingController();
    return showDialog<String>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('$action Consultation'),
        content: TextField(
          controller: controller,
          decoration: InputDecoration(
            hintText: 'Optional reason...',
            border: OutlineInputBorder(borderRadius: BorderRadius.circular(AppRadius.sm)),
          ),
          maxLines: 3,
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
          FilledButton(onPressed: () => Navigator.pop(context, controller.text), child: Text(action)),
        ],
      ),
    );
  }
}
