import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../../core/constants/app_constants.dart';
import '../../../core/services/auth_service.dart';
import '../../chat/services/chat_service.dart';
import '../../chat/models/message_model.dart';
import '../../cases/models/consultation_model.dart';
import '../../cases/services/consultation_service.dart';
import '../../wallet/services/wallet_service.dart';

/// Booking Summary Screen - Review and confirm payment
class BookingSummaryScreen extends StatefulWidget {
  final Map<String, dynamic> bookingData;

  const BookingSummaryScreen({
    super.key,
    required this.bookingData,
  });

  @override
  State<BookingSummaryScreen> createState() => _BookingSummaryScreenState();
}

class _BookingSummaryScreenState extends State<BookingSummaryScreen> {
  bool _isProcessing = false;
  final AuthService _authService = AuthService();
  final WalletService _walletService = WalletService();

  Future<void> _confirmPayment() async {
    if (_isProcessing) return;
    final price = (widget.bookingData['price'] as num).toInt();
    final lawyerId = widget.bookingData['lawyerId'] as String;
    final lawyerName = widget.bookingData['lawyerName'] as String;
    final lawyerAvatar = widget.bookingData['lawyerAvatar'] as String?;
    final lawyerSpecialization = widget.bookingData['lawyerSpecialization'] as String;
    final topic = widget.bookingData['topic'] as String;
    final meetingType = widget.bookingData['meetingType'] as String;
    final date = widget.bookingData['date'] as DateTime;
    final time = widget.bookingData['time'] as String;

    final currentUser = _authService.currentUser;
    if (currentUser == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('User not logged in'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    final balance = await _walletService.getWalletBalance(currentUser.uid);

    if (!context.mounted) return;
    if (balance < price) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Insufficient balance. Please add funds.'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    setState(() => _isProcessing = true);

    var debitDone = false;
    try {

      // Check for existing active consultations between these two users
      final existingConsultations = await FirebaseFirestore.instance
          .collection('cases')
          .doc('standalone')
          .collection('consultations')
          .where('requesterId', isEqualTo: currentUser.uid)
          .where('targetId', isEqualTo: lawyerId)
          .where('status', whereIn: ['pending', 'accepted'])
          .get();

      if (!context.mounted) return;

      if (existingConsultations.docs.isNotEmpty) {
        throw Exception('You already have an active or pending consultation with this lawyer. Please wait for it to conclude before booking another one.');
      }

      final userData = await _authService.getUserData(currentUser.uid);
      if (!context.mounted) return;
      final clientName = userData?['fullName'] ?? 'Client';
      final clientAvatar = userData?['photoUrl'];

      // 1. Get or Create Chat
      final chatService = ChatService();
      final chat = await chatService.getOrCreateChat(
        clientId: currentUser.uid,
        lawyerId: lawyerId,
        clientName: clientName,
        lawyerName: lawyerName,
        clientAvatar: clientAvatar,
        lawyerAvatar: lawyerAvatar,
      );

      if (!context.mounted) return;

      // Generate Consultation ID early so we can pass it to message
      final consultationId = FirebaseFirestore.instance.collection('tmp').doc().id;
      final operationId =
          'consultation_booking_${currentUser.uid}_$consultationId';

      await _walletService.debit(
        userId: currentUser.uid,
        amount: price.toDouble(),
        reason: 'consultation_booking',
        operationId: operationId,
        counterpartyUserId: lawyerId,
        referenceType: 'consultation',
        referenceId: consultationId,
        metadata: {
          'lawyerName': lawyerName,
          'topic': topic,
        },
      );
      if (!context.mounted) return;
      debitDone = true;

      // 2. Create Consultation Message
      final message = MessageModel(
        id: '', // Generated by ChatService
        senderId: currentUser.uid,
        text: 'Consultation Request: $topic',
        timestamp: DateTime.now(),
        type: 'consultation_booking',
        metadata: {
          'consultationId': consultationId,
          'caseId': 'standalone',
          'topic': topic,
          'meetingType': meetingType,
          'date': date.toIso8601String(),
          'time': time,
          'price': price,
          'status': 'pending',
          'lawyerSpecialization': lawyerSpecialization,
        },
      );

      // 3. Send Message
      await chatService.sendMessage(chat.id, message, false);
      if (!context.mounted) return;

      // 4. Create Consultation Record for the Consultations tab
      final consultationService = ConsultationService();
      
      final scheduledAt = DateTime(
        date.year,
        date.month,
        date.day,
        _parseHour(time),
        _parseMinute(time),
      );

      final consultation = ConsultationModel(
        id: consultationId,
        caseId: 'standalone',
        requesterId: currentUser.uid,
        targetId: lawyerId,
        caseTitle: '$topic Consultation',
        clientName: clientName,
        lawyerName: lawyerName,
        clientId: currentUser.uid,
        lawyerId: lawyerId,
        clientAvatar: clientAvatar,
        lawyerAvatar: lawyerAvatar,
        type: meetingType == 'online' ? 'video' : 'in_person',
        description: topic,
        status: 'pending',
        scheduledAt: scheduledAt,
        createdAt: DateTime.now(),
        caseStatus: 'active',
      );

      await consultationService.requestConsultation(consultation, clientName, 'Client');

      if (!context.mounted) return;
      setState(() => _isProcessing = false);

      // Navigate to Chat Screen
      context.pushReplacement('/chat/${chat.id}', extra: {
        'lawyerId': lawyerId,
        'lawyerName': lawyerName,
        'lawyerAvatar': lawyerAvatar,
        'isOnline': true,
      });

    } catch (e) {
      if (debitDone) {
        // Best-effort rollback if debit happened and later steps failed.
        try {
          final consultationId = FirebaseFirestore.instance.collection('tmp').doc().id;
          await _walletService.credit(
            userId: currentUser.uid,
            amount: (widget.bookingData['price'] as num).toDouble(),
            reason: 'consultation_booking_refund',
            operationId:
                'consultation_refund_${currentUser.uid}_${DateTime.now().microsecondsSinceEpoch}',
            metadata: {'cause': 'booking_create_failed', 'tempId': consultationId},
          );
        } catch (_) {}
      }
      if (!context.mounted) return;
      setState(() => _isProcessing = false);
      final errorMsg = e.toString().replaceAll('Exception: ', '');
      showDialog(
        context: context,
        builder: (context) => Dialog(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(AppRadius.lg),
          ),
          child: Padding(
            padding: const EdgeInsets.all(AppSpacing.lg),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Container(
                  padding: const EdgeInsets.all(AppSpacing.md),
                  decoration: BoxDecoration(
                    color: AppColors.error.withValues(alpha: 0.1),
                    shape: BoxShape.circle,
                  ),
                  child: PhosphorIcon(
                    PhosphorIconsRegular.warningCircle,
                    color: AppColors.error,
                    size: 32,
                  ),
                ),
                const SizedBox(height: AppSpacing.md),
                Text(
                  'Booking Unavailable',
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                    color: AppColors.textPrimary,
                  ),
                ),
                const SizedBox(height: AppSpacing.sm),
                Text(
                  errorMsg,
                  textAlign: TextAlign.center,
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    color: AppColors.textSecondary,
                  ),
                ),
                const SizedBox(height: AppSpacing.lg),
                Row(
                  children: [
                    Expanded(
                      child: TextButton(
                        onPressed: () => Navigator.pop(context),
                        style: TextButton.styleFrom(
                          padding: const EdgeInsets.symmetric(vertical: AppSpacing.md),
                        ),
                        child: const Text('Cancel'),
                      ),
                    ),
                    const SizedBox(width: AppSpacing.sm),
                    Expanded(
                      child: ElevatedButton(
                        onPressed: () {
                          Navigator.pop(context);
                          context.go('/client-messages'); // Direct them to their active chats
                        },
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.primary,
                          padding: const EdgeInsets.symmetric(vertical: AppSpacing.md),
                        ),
                        child: const Text('Go to Chats'),
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;
    final lawyerName = widget.bookingData['lawyerName'] as String;
    final lawyerAvatar = widget.bookingData['lawyerAvatar'] as String?;
    final lawyerSpecialization = widget.bookingData['lawyerSpecialization'] as String;
    final topic = widget.bookingData['topic'] as String;
    final meetingType = widget.bookingData['meetingType'] as String;
    final date = widget.bookingData['date'] as DateTime;
    final time = widget.bookingData['time'] as String;
    final price = (widget.bookingData['price'] as num).toInt();

    final currentUser = _authService.currentUser;
    if (currentUser == null) {
      return const Scaffold(
        body: Center(child: Text('Please login to continue')),
      );
    }

    return StreamBuilder<double>(
      stream: _walletService.streamWalletBalance(currentUser.uid),
      builder: (context, walletSnapshot) {
        final walletBalance = walletSnapshot.data ?? 0;
        final hasSufficientBalance = walletBalance >= price;

        return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.surface,
        elevation: 0,
        leading: IconButton(
          icon: const PhosphorIcon(PhosphorIconsRegular.arrowLeft),
          onPressed: () => context.pop(),
        ),
        title: Text(
          'Booking Summary',
          style: textTheme.headlineSmall?.copyWith(
            color: AppColors.primary,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(AppSpacing.lg),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Lawyer Card
                  _InfoCard(
                    icon: PhosphorIconsRegular.user,
                    title: 'Lawyer',
                    child: Row(
                      children: [
                        CircleAvatar(
                          radius: 25,
                          backgroundImage: lawyerAvatar != null 
                              ? NetworkImage(lawyerAvatar) 
                              : const NetworkImage('https://ui-avatars.com/api/?name=Lawyer&background=random'),
                        ),
                        const SizedBox(width: AppSpacing.md),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                lawyerName,
                                style: textTheme.titleMedium?.copyWith(
                                  fontWeight: FontWeight.w700,
                                ),
                              ),
                              Text(
                                '$lawyerSpecialization Consultation',
                                style: textTheme.bodySmall?.copyWith(
                                  color: AppColors.textSecondary,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: AppSpacing.md),

                  // Schedule Card
                  _InfoCard(
                    icon: PhosphorIconsRegular.calendar,
                    title: 'Schedule',
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            const PhosphorIcon(
                              PhosphorIconsRegular.calendarBlank,
                              size: 18,
                              color: AppColors.secondary,
                            ),
                            const SizedBox(width: AppSpacing.sm),
                            Text(
                              _formatDate(date),
                              style: textTheme.bodyMedium?.copyWith(
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: AppSpacing.sm),
                        Row(
                          children: [
                            const PhosphorIcon(
                              PhosphorIconsRegular.clock,
                              size: 18,
                              color: AppColors.secondary,
                            ),
                            const SizedBox(width: AppSpacing.sm),
                            Text(
                              time,
                              style: textTheme.bodyMedium?.copyWith(
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),

                  const SizedBox(height: AppSpacing.md),

                  // Payment Card
                  _InfoCard(
                    icon: PhosphorIconsRegular.wallet,
                    title: 'Payment Details',
                    child: Column(
                      children: [
                        // Topic
                        Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              'Topic',
                              style: textTheme.bodyMedium?.copyWith(
                                color: AppColors.textSecondary,
                              ),
                            ),
                            const Spacer(),
                            Expanded(
                              flex: 2,
                              child: Text(
                                topic,
                                style: textTheme.bodyMedium?.copyWith(
                                  fontWeight: FontWeight.w600,
                                ),
                                textAlign: TextAlign.right,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: AppSpacing.sm),
                        
                        // Meeting Type
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              'Meeting Type',
                              style: textTheme.bodyMedium?.copyWith(
                                color: AppColors.textSecondary,
                              ),
                            ),
                            Text(
                              meetingType == 'online' ? 'Video Call' : 'In-Person',
                              style: textTheme.bodyMedium?.copyWith(
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: AppSpacing.md),
                        const Divider(),
                        const SizedBox(height: AppSpacing.md),
                        
                        // Consultation Fee
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              'Consultation Fee',
                              style: textTheme.bodyMedium?.copyWith(
                                color: AppColors.textSecondary,
                              ),
                            ),
                            Text(
                              'PKR $price',
                              style: textTheme.titleMedium?.copyWith(
                                fontWeight: FontWeight.w700,
                              ),
                            ),
                          ],
                        ),

                        const SizedBox(height: AppSpacing.md),
                        const Divider(),
                        const SizedBox(height: AppSpacing.md),

                        // Wallet Balance
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Text(
                              'Wallet Balance',
                              style: textTheme.bodyMedium?.copyWith(
                                color: AppColors.textSecondary,
                              ),
                            ),
                            Row(
                              children: [
                                Text(
                                  'PKR ${walletBalance.toStringAsFixed(0)}',
                                  style: textTheme.titleMedium?.copyWith(
                                    color: hasSufficientBalance
                                        ? AppColors.success
                                        : AppColors.error,
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                                const SizedBox(width: AppSpacing.xs),
                                PhosphorIcon(
                                  hasSufficientBalance
                                      ? PhosphorIconsFill.checkCircle
                                      : PhosphorIconsFill.warningCircle,
                                  size: 20,
                                  color: hasSufficientBalance
                                      ? AppColors.success
                                      : AppColors.error,
                                ),
                              ],
                            ),
                          ],
                        ),

                        // Insufficient Balance Warning
                        if (!hasSufficientBalance) ...[
                          const SizedBox(height: AppSpacing.md),
                          Container(
                            padding: const EdgeInsets.all(AppSpacing.md),
                            decoration: BoxDecoration(
                              color: AppColors.error.withValues(alpha: 0.1),
                              borderRadius: BorderRadius.circular(AppRadius.sm),
                              border: Border.all(
                                color: AppColors.error.withValues(alpha: 0.3),
                              ),
                            ),
                            child: Row(
                              children: [
                                const PhosphorIcon(
                                  PhosphorIconsRegular.warning,
                                  size: 20,
                                  color: AppColors.error,
                                ),
                                const SizedBox(width: AppSpacing.sm),
                                Expanded(
                                  child: Text(
                                    'Insufficient balance. Please add funds.',
                                    style: textTheme.bodySmall?.copyWith(
                                      color: AppColors.error,
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(height: AppSpacing.sm),
                          SizedBox(
                            width: double.infinity,
                            child: OutlinedButton.icon(
                              onPressed: () {
                                context.push('/wallet');
                              },
                              icon: const PhosphorIcon(
                                PhosphorIconsRegular.plus,
                                size: 18,
                              ),
                              label: const Text('Add Funds'),
                              style: OutlinedButton.styleFrom(
                                foregroundColor: AppColors.secondary,
                                side: const BorderSide(
                                  color: AppColors.secondary,
                                ),
                              ),
                            ),
                          ),
                        ],
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),

          // Bottom Action Bar
          Container(
            padding: const EdgeInsets.all(AppSpacing.lg),
            decoration: BoxDecoration(
              color: AppColors.surface,
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.1),
                  blurRadius: 8,
                  offset: const Offset(0, -2),
                ),
              ],
            ),
            child: SafeArea(
              child: SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _isProcessing || !hasSufficientBalance
                      ? null
                      : _confirmPayment,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primary,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(
                      vertical: AppSpacing.md,
                    ),
                    disabledBackgroundColor: AppColors.grey300,
                  ),
                  child: _isProcessing
                      ? Row(
                          mainAxisAlignment: MainAxisAlignment.center,
                          children: [
                            const SizedBox(
                              height: 20,
                              width: 20,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                valueColor:
                                    AlwaysStoppedAnimation<Color>(Colors.white),
                              ),
                            ),
                            const SizedBox(width: AppSpacing.md),
                            const Text('Processing Payment...'),
                          ],
                        )
                      : const Text('Confirm Payment'),
                ),
              ),
            ),
          ),
        ],
      ),
    );
      },
    );
  }

  String _formatDate(DateTime date) {
    const weekdays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    const months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec'
    ];
    return '${weekdays[date.weekday - 1]}, ${date.day} ${months[date.month - 1]} ${date.year}';
  }

  int _parseHour(String timeStr) {
    try {
      final parts = timeStr.split(' ');
      if (parts.length < 2) return 9; // Fallback
      final hm = parts[0].split(':');
      int hour = int.parse(hm[0]);
      final ampm = parts[1].toUpperCase();
      if (ampm == 'PM' && hour < 12) hour += 12;
      if (ampm == 'AM' && hour == 12) hour = 0;
      return hour;
    } catch (_) {
      return 9;
    }
  }

  int _parseMinute(String timeStr) {
    try {
      return int.parse(timeStr.split(' ')[0].split(':')[1]);
    } catch (_) {
      return 0;
    }
  }
}

/// Info Card Widget
class _InfoCard extends StatelessWidget {
  final PhosphorIconData icon;
  final String title;
  final Widget child;

  const _InfoCard({
    required this.icon,
    required this.title,
    required this.child,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final textTheme = theme.textTheme;

    return Container(
      padding: const EdgeInsets.all(AppSpacing.md),
      decoration: BoxDecoration(
        color: AppColors.surface,
        borderRadius: BorderRadius.circular(AppRadius.md),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              PhosphorIcon(
                icon,
                size: 20,
                color: AppColors.secondary,
              ),
              const SizedBox(width: AppSpacing.sm),
              Text(
                title,
                style: textTheme.labelLarge?.copyWith(
                  color: AppColors.textSecondary,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
          const SizedBox(height: AppSpacing.md),
          child,
        ],
      ),
    );
  }
}
